# States obtained from PEPA Eclipse plugin in State Space View
model_states = [
    ["MUn","EnvUn","MF","EnvF","MLV","EnvLV","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","VEnvUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","EnvLV","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","VEnvUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","MLV","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","MLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","VEnv2L","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","EnvLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","VEnv1L","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","VEnv2L","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","EnvLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","VEnv1L","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","VUnL","VEnvUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","VUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","VUnL","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","VEnvUnL","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnvUnL","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","VFL","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","VFL","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","VEnvFL","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","EnvLV","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","VUnL","VUnL","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","MLV","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","MLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","VLVL","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","MLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","VLVL","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","VEnv2L","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","VEnv1L","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnv2L","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnv1L","C"],
    ["MUinv","EnvUinv","MF","EnvF","VUnL","VEnvUnL","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","MLV","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","VUnL","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VUnL","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","MLV","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","VFL","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VFL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","VFL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","VFL","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","EnvLV","C"],
    ["MUinv","EnvUinv","MF","EnvF","VUnL","VUnL","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","VLVL","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VLVL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","VEnv1L","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","VEnv1L","C"],
    ["MUinv","EnvUinv","MF","EnvF","MLV","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","VFL","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","EnvLV","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","VFL","C"],
    ["MUinv","EnvUinv","MF","EnvF","MLV","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","VEnv1L","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","VEnv1L","C"]
    # ["MUn","EnvUn","MF","EnvF"],
    # ["MUn","EnvUn","VUn","VEnvUn"],
    # ["MUn","EnvUn","VF","VEnv2"],
    # ["MUn","EnvUn","VF","VEnv1"],
    # ["MUn","EnvUn","VF","EnvF"]
]

ctmc_states = {
    "(MUn, EnvUn, MF, EnvF)": "1",
    "(MUn, EnvUn, VUn, VEnvUn)": "2",
    "(MUn, EnvUn, VF, VEnv2)": "3",
    "(MUn, EnvUn, VF, VEnv1)": "4",
    "(MUn, EnvUn, VF, EnvF)": "5"
}