# States obtained from PEPA Eclipse plugin in State Space View
model_states = [
    ["MUn","EnvUn","MF","EnvF","MLV","EnvLV","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","VEnvUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","EnvLV","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","VEnvUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","MLV","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","MLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","VEnv2L","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","EnvLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","VEnv1L","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","VEnv2L","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","EnvLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","VEnv1L","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","VUnL","VEnvUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","VUnL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","VUnL","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","VEnvUnL","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnvUnL","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","VFL","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","VFL","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","VEnvFL","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","VEnvFL","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","EnvLV","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","VUnL","VUnL","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","VEnvFL","C"],
    ["MUn","EnvUn","VUn","VEnvUn","VUnL","MLV","C"],
    ["MUn","EnvUn","VUn","VEnvUn","MLV","MLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","VLVL","C"],
    ["MUn","EnvUn","VLV","VEnvLV","VLVL","MLV","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","VLVL","C"],
    ["MUn","EnvUn","VLV","VEnvLV","MLV","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","VEnv2L","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","VEnv1L","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnv2L","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VEnv1L","C"],
    ["MUinv","EnvUinv","MF","EnvF","VUnL","VEnvUnL","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","MLV","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","VUnL","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VUnL","C"],
    ["MUn","EnvUn","VF","VEnv2","VFL","MLV","C"],
    ["MUn","EnvUn","VF","VEnv2","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","VFL","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VFL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","VFL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","EnvLV","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","VFL","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","EnvLV","C"],
    ["MUinv","EnvUinv","MF","EnvF","VUnL","VUnL","C"],
    ["MUinv","EnvUinv","VUn","VEnvUn","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VUnL","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","VLVL","C"],
    ["MUn","EnvUn","MF","EnvF","VLVL","MLV","C"],
    ["MUn","EnvUn","MF","EnvF","MLV","VLVL","C"],
    ["MUn","EnvUn","VF","VEnv1","VFL","VEnv1L","C"],
    ["MUn","EnvUn","VF","VEnv1","MLV","VEnv1L","C"],
    ["MUinv","EnvUinv","MF","EnvF","MLV","EnvLV","C"],
    ["MUn","EnvUn","MF","EnvF","VFL","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","VFL","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","EnvLV","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","VFL","C"],
    ["MUinv","EnvUinv","MF","EnvF","MLV","MLV","C"],
    ["MUn","EnvUn","VF","EnvF","VFL","VEnv1L","C"],
    ["MUn","EnvUn","VF","EnvF","MLV","VEnv1L","C"]
    # ["MUn","EnvUn","MF","EnvF"],
    # ["MUn","EnvUn","VUn","VEnvUn"],
    # ["MUn","EnvUn","VF","VEnv2"],
    # ["MUn","EnvUn","VF","VEnv1"],
    # ["MUn","EnvUn","VF","EnvF"]
]

ctmc_states = {
    # "(MUn, EnvUn, MF, EnvF)": "1",
    # "(MUn, EnvUn, VUn, VEnvUn)": "2",
    # "(MUn, EnvUn, VF, VEnv2)": "3",
    # "(MUn, EnvUn, VF, VEnv1)": "4",
    # "(MUn, EnvUn, VF, EnvF)": "5"
    "(MUn, EnvUn, MF, EnvF, MLV, EnvLV, C)": "1", 
    "(MUn, EnvUn, VUn, VEnvUn, VUnL, VEnvUnL, C)": "2", 
    "(MUn, EnvUn, VUn, VEnvUn, VUnL, EnvLV, C)": "3", 
    "(MUn, EnvUn, VUn, VEnvUn, MLV, VEnvUnL, C)": "4", 
    "(MUn, EnvUn, VUn, VEnvUn, MLV, EnvLV, C)": "5", 
    "(MUn, EnvUn, VF, VEnv2, VFL, VEnvFL, C)": "6", 
    "(MUn, EnvUn, VF, VEnv2, VFL, EnvLV, C)": "7", 
    "(MUn, EnvUn, VF, VEnv2, MLV, VEnvFL, C)": "8", 
    "(MUn, EnvUn, VF, VEnv2, MLV, EnvLV, C)": "9", 
    "(MUn, EnvUn, VF, VEnv1, VFL, VEnvFL, C)": "10", 
    "(MUn, EnvUn, VF, VEnv1, VFL, MLV, C)": "11", 
    "(MUn, EnvUn, VF, VEnv1, MLV, VEnvFL, C)": "12", 
    "(MUn, EnvUn, VF, VEnv1, MLV, MLV, C)": "13", 
    "(MUn, EnvUn, VLV, VEnvLV, VLVL, VEnv2L, C)": "14", 
    "(MUn, EnvUn, VLV, VEnvLV, VLVL, EnvLV, C)": "15", 
    "(MUn, EnvUn, VLV, VEnvLV, VLVL, VEnv1L, C)": "16", 
    "(MUn, EnvUn, VLV, VEnvLV, MLV, VEnv2L, C)": "17", 
    "(MUn, EnvUn, VLV, VEnvLV, MLV, EnvLV, C)": "18", 
    "(MUn, EnvUn, VLV, VEnvLV, MLV, VEnv1L, C)": "19", 
    "(MUinv, EnvUinv, VUn, VEnvUn, VUnL, VEnvUnL, C)": "20", 
    "(MUn, EnvUn, VUn, VEnvUn, VUnL, VUnL, C)": "21", 
    "(MUn, EnvUn, VUn, VEnvUn, MLV, VUnL, C)": "22", 
    "(MUn, EnvUn, MF, EnvF, VUnL, VEnvUnL, C)": "23", 
    "(MUn, EnvUn, MF, EnvF, VUnL, EnvLV, C)": "24", 
    "(MUn, EnvUn, MF, EnvF, MLV, VEnvUnL, C)": "25", 
    "(MUn, EnvUn, VF, VEnv2, VFL, VFL, C)": "26", 
    "(MUn, EnvUn, VF, VEnv2, MLV, VFL, C)": "27", 
    "(MUn, EnvUn, MF, EnvF, VFL, VEnvFL, C)": "28", 
    "(MUn, EnvUn, MF, EnvF, VFL, EnvLV, C)": "29", 
    "(MUn, EnvUn, MF, EnvF, MLV, VEnvFL, C)": "30", 
    "(MUn, EnvUn, VF, EnvF, VFL, VEnvFL, C)": "31", 
    "(MUn, EnvUn, VF, VEnv1, MLV, EnvLV, C)": "32", 
    "(MUinv, EnvUinv, VUn, VEnvUn, VUnL, VUnL, C)": "33", 
    "(MUn, EnvUn, VF, EnvF, VFL, MLV, C)": "34", 
    "(MUn, EnvUn, VF, EnvF, MLV, VEnvFL, C)": "35", 
    "(MUn, EnvUn, VUn, VEnvUn, VUnL, MLV, C)": "36", 
    "(MUn, EnvUn, VUn, VEnvUn, MLV, MLV, C)": "37", 
    "(MUn, EnvUn, VLV, VEnvLV, VLVL, VLVL, C)": "38", 
    "(MUn, EnvUn, VLV, VEnvLV, VLVL, MLV, C)": "39", 
    "(MUn, EnvUn, VLV, VEnvLV, MLV, VLVL, C)": "40", 
    "(MUn, EnvUn, VLV, VEnvLV, MLV, MLV, C)": "41", 
    "(MUn, EnvUn, VF, EnvF, MLV, MLV, C)": "42", 
    "(MUn, EnvUn, MF, EnvF, VLVL, VEnv2L, C)": "43", 
    "(MUn, EnvUn, MF, EnvF, VLVL, EnvLV, C)": "44", 
    "(MUn, EnvUn, MF, EnvF, VLVL, VEnv1L, C)": "45", 
    "(MUn, EnvUn, MF, EnvF, MLV, VEnv2L, C)": "46", 
    "(MUn, EnvUn, MF, EnvF, MLV, VEnv1L, C)": "47", 
    "(MUinv, EnvUinv, MF, EnvF, VUnL, VEnvUnL, C)": "48", 
    "(MUinv, EnvUinv, VUn, VEnvUn, MLV, EnvLV, C)": "49", 
    "(MUn, EnvUn, MF, EnvF, VUnL, VUnL, C)": "50", 
    "(MUn, EnvUn, MF, EnvF, MLV, VUnL, C)": "51", 
    "(MUn, EnvUn, VF, VEnv2, VFL, MLV, C)": "52", 
    "(MUn, EnvUn, VF, VEnv2, MLV, MLV, C)": "53", 
    "(MUn, EnvUn, MF, EnvF, VFL, VFL, C)": "54", 
    "(MUn, EnvUn, MF, EnvF, MLV, VFL, C)": "55", 
    "(MUn, EnvUn, VF, VEnv1, VFL, VFL, C)": "56", 
    "(MUn, EnvUn, VF, VEnv1, VFL, EnvLV, C)": "57", 
    "(MUn, EnvUn, VF, VEnv1, MLV, VFL, C)": "58", 
    "(MUn, EnvUn, VF, EnvF, MLV, EnvLV, C)": "59", 
    "(MUinv, EnvUinv, MF, EnvF, VUnL, VUnL, C)": "60", 
    "(MUinv, EnvUinv, VUn, VEnvUn, MLV, MLV, C)": "61", 
    "(MUn, EnvUn, MF, EnvF, VUnL, MLV, C)": "62", 
    "(MUn, EnvUn, MF, EnvF, MLV, MLV, C)": "63", 
    "(MUn, EnvUn, MF, EnvF, VLVL, VLVL, C)": "64", 
    "(MUn, EnvUn, MF, EnvF, VLVL, MLV, C)": "65", 
    "(MUn, EnvUn, MF, EnvF, MLV, VLVL, C)": "66", 
    "(MUn, EnvUn, VF, VEnv1, VFL, VEnv1L, C)": "67", 
    "(MUn, EnvUn, VF, VEnv1, MLV, VEnv1L, C)": "68", 
    "(MUinv, EnvUinv, MF, EnvF, MLV, EnvLV, C)": "69", 
    "(MUn, EnvUn, MF, EnvF, VFL, MLV, C)": "70", 
    "(MUn, EnvUn, VF, EnvF, VFL, VFL, C)": "71", 
    "(MUn, EnvUn, VF, EnvF, VFL, EnvLV, C)": "72", 
    "(MUn, EnvUn, VF, EnvF, MLV, VFL, C)": "73", 
    "(MUinv, EnvUinv, MF, EnvF, MLV, MLV, C)": "74", 
    "(MUn, EnvUn, VF, EnvF, VFL, VEnv1L, C)": "75", 
    "(MUn, EnvUn, VF, EnvF, MLV, VEnv1L, C)": "76"
}